### PR TITLE
use TrustedRedirectResponse to allow redirect to external url / subdo…

### PR DESCRIPTION
**Pull request by youpixxl**

### CODE REVIEW

**Comment by pvbergen** [comment]
Thanks for the adjustments. Having TrustedRedirectResponse for node, term and user is actually not necessary (they are always internal), but let's keep it like that 🙂

Is the normal RedirectResponse still used? If not, we can remove the use statement.

**Comment by youpixxl** [comment]
Hi Philippe
Sorry I asked your review too soon!
I am still working on it, I have issue with cache metadata when using TrustedRedirectResponse. I will push as soon as I have something working

**Comment by youpixxl** [comment]
Ok I think it should work now.

The issue: 
TrustedRedirectResponse is a cacheable response and will fail if cache is not propery set/define (see https://drupal.stackexchange.com/questions/187086/trustedresponseredirect-failing-how-to-prevent-cache-metadata and https://drupal.stackexchange.com/questions/225189/how-do-i-redirect-to-an-external-url-without-caching-it).

I realized the createURL() function use the TokenService, which will insert local cache. To prevent it I just added an empty object as described in the Token Service Class.

What do you think?

**Comment by pvbergen** [comment]
I'm confused about the cache issue. The token service should add the necessary cache tags from the entity (node, user, term, redirect). If you change the entity, it should invalidate the cache.
In what scenario did you have the caching issues?

**Comment by youpixxl** [comment]
I think the problem is not that the cache is not defined, actually it is the contrary: defining the cache with local value cause trouble on a trusted redirect response...
If you test this branch and use the TrustedRedirectResponse without the BubbleableMetadata it will throw you this error:

`Auf der Website ist ein unvorhergesehener Fehler aufgetreten. Bitte versuchen Sie es später nochmal.

LogicException: The controller result claims to be providing relevant cache metadata, but leaked metadata was detected. Please ensure you are not rendering content too early. Returned object class: Drupal\Core\Routing\TrustedRedirectResponse. in Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext() (line 154 of core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php).
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 158)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 80)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 41)
Drupal\iqual\Middleware\Redirect->handle(Object, 1, 1) (Line: 58)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 708)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)`

**Comment by pvbergen** [comment]
Ah, now I understand, thanks. The solution then makes sense 🙂

**Review by pvbergen — APPROVED** [review]
Looks good, ready to merge and release.

**Pull request merged**
